#
# 服务器 配置
server:
  # 端口
  port: 8080
#
# Spring Boot 配置
spring:
  #
  # 数据库 配置
  datasource:
    # 数据库 驱动名称（包括包名）
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库 URL
    url: jdbc:mysql://127.0.0.1:3306/jsf-ri?useSSL=false&serverTimezone=GMT%2B8
    # 数据库 用户名
    username: root
    # 数据库 密码
    password: root
  #
  # Redis 配置
  redis:
    # 数据库名称，默认为 db0
    # 连接工厂使用的数据库索引。
    database: 1
    # Redis服务器主机。
    host: 127.0.0.1
    # redis服务器的登录密码。
    password:
    # Redis服务器端口。
    port: 6379
#
# 日志 配置
logging:
  level:
    web: debug
    cn.com.xuxiaowei: debug
