#
# 服务器 配置
server:
  # 端口
  port: 8080
#
# Spring Boot 配置
spring:
  #
  # Redis 配置
  redis:
    # 数据库名称，默认为 db0
    # 连接工厂使用的数据库索引。
    database: 1
    # Redis服务器主机。
    host: 127.0.0.1
    # redis服务器的登录密码。
    password:
    # Redis服务器端口。
    port: 6379
#
# 日志 配置
logging:
  level:
    web: debug
    cn.com.xuxiaowei: debug
